[package]
name = "proofr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
nom = "7.1.3" 
rand = "0.9.2"
regex = "1.11.1"
serde_yaml = "0.9.34"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
