name: SonarQube Analysis
on:
  push:
    branches:
    - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    container:
      image: cimg/rust:1.83.0-node  # Use a Rust-enabled image

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Rust analysis dependencies
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --version
          cargo clippy --version
      
      - name: Install and run SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-aarch64.zip
          unzip sonar-scanner-cli-6.2.1.4610-linux-aarch64.zip
          echo "sonar-scanner path: $(pwd)/sonar-scanner-6.2.1.4610-linux-aarch64/bin"
          export PATH="$(pwd)/sonar-scanner-6.2.1.4610-linux-aarch64/bin:$PATH"
          sonar-scanner --version
          cargo tarpaulin --all-features --out Xml
          cargo clippy --message-format=json &> clippy.json
          sonar-scanner -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
